### ISSUE TITLE
[feat] 앨범 선택 화면 기능개선

### ISSUE THREAD

**Issue by wongbingg** [wongbingg/Particle#1]
## TODO

- [x] 앨범 내 카테고리 가져오기
- [x] 선택한 사진, 동영상 가로 리스트 뷰 
- [x] 앨범 내 소스 실시간 업데이트
- [x] 앨범 카테고리 선택 UI
- [x] 앨범 사진 불러오는 속도 높이기

**Comment by wongbingg** [comment]
<img width="1840" alt="스크린샷 2024-06-26 오후 10 16 10" src="https://github.com/wongbingg/Particle/assets/95671495/6a663c94-6eed-459a-828a-cf31920ceca1">
